services:
  project-proxy:
    container_name: project-proxy
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy:/data/caddy
    networks:
      - internal
    depends_on:
      - project-backend

  project-backend:
    container_name: project-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - DATABASE_HOST=project-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=database
    networks:
      - internal
    depends_on:
      - project-mysql

  project-mysql:
    container_name: project-mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  mysql-data:
    driver: local
