FROM rust:1.85-alpine3.20

WORKDIR /app

RUN apk add --no-cache musl-dev gcc g++ make && \
    cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./

RUN mkdir -p ./src && \
    echo "fn main() {}" > ./src/main.rs && \
    cargo build --release && \
    rm -rf ./src

COPY . .

CMD ["cargo", "watch", "-x", "run"]
