FROM rust:1.85-alpine3.20 as builder
WORKDIR /app

RUN apk add --no-cache musl-dev gcc g++ make

COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN cargo build --release

FROM alpine:3.20
WORKDIR /app
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/target/release/backend .
ENTRYPOINT ["/app/backend"]
